# Generated by Django 4.2.13 on 2024-06-04 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='название книги')),
                ('description', models.CharField(default='', max_length=2000, null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
                ('authors_note', models.CharField(blank=True, max_length=2000, null=True, verbose_name='примечание автора')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='дата редактирования')),
                ('slug', models.SlugField(verbose_name='название ссылки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='текст комментария')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата написания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='app_market.book', verbose_name='книга')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, verbose_name='теги')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название жанра')),
                ('slug', models.SlugField(verbose_name='название ссылки')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgenre', to='app_market.genre', verbose_name='родительский жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='название цикла')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='описание цикла')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('update_date', models.DateField(auto_now=True, null=True, verbose_name='дата редактирования')),
                ('completed', models.BooleanField()),
                ('slug', models.SlugField(verbose_name='название ссылки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
            },
        ),
        migrations.CreateModel(
            name='BookReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/books/%Y/%m', verbose_name='картинка')),
                ('image_alt', models.CharField(default='Изображение к отзыву', max_length=100, verbose_name='подсказка')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_market.bookreview', verbose_name='отзыв')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/books/%Y/%m', verbose_name='обложка книги')),
                ('image_alt', models.CharField(default='Обложка книги', max_length=100, verbose_name='подсказка')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_market.book', verbose_name='книга')),
            ],
            options={
                'verbose_name': 'Обложка',
                'verbose_name_plural': 'Обложки',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app_market.cycle', verbose_name='цикл'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(default=None, related_name='books', to='app_market.genre', verbose_name='жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='books', to='app_market.tag', verbose_name='теги'),
        ),
    ]
