# Generated by Django 4.2.13 on 2024-05-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/books/%Y/%m', verbose_name='Обложка книги')),
                ('image_alt', models.CharField(default='Обложка книги', max_length=100, verbose_name='Подсказка')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_market.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Обложка',
                'verbose_name_plural': 'Обложки',
            },
        ),
    ]
