# Generated by Django 4.2.13 on 2024-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='описание цикла'),
        ),
    ]
