# Generated by Django 4.2.13 on 2024-05-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_alter_bookimage_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_market.book', verbose_name='Книга'),
        ),
    ]
