# Generated by Django 4.2.13 on 2024-05-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_market', '0005_bookreview_alter_book_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors_note',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='примечание автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(verbose_name='название ссылки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_market.book', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(upload_to='images/books/%Y/%m', verbose_name='обложка книги'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image_alt',
            field=models.CharField(default='Обложка книги', max_length=100, verbose_name='подсказка'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата написания'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='текст комментария'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='описание цикла'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='slug',
            field=models.SlugField(verbose_name='название ссылки'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgenre', to='app_market.genre', verbose_name='родительский жанр'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(verbose_name='название ссылки'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='теги'),
        ),
    ]
