# Generated by Django 4.2.13 on 2024-06-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='app_profile.profile', verbose_name='пользователь'),
        ),
    ]
