# Generated by Django 4.2.13 on 2024-10-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_alter_profileavatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='app_profile.profile', verbose_name='пользователь'),
        ),
    ]
