# Generated by Django 4.2.13 on 2024-10-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0004_alter_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='номер телефона'),
        ),
    ]
