# Generated by Django 4.2.13 on 2024-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='название сайта')),
                ('phone_number1', models.CharField(max_length=255, verbose_name='номер телефона 1')),
                ('phone_number2', models.CharField(max_length=255, verbose_name='номер телефона 2')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('banner_number', models.PositiveSmallIntegerField(verbose_name='количество баннеров')),
                ('stopping_sales', models.BooleanField(default=False, verbose_name='остановка продаж')),
                ('banner_cache_time', models.PositiveIntegerField(verbose_name='кэш баннеров')),
                ('total_cache_time', models.PositiveIntegerField(verbose_name='общий кэш')),
                ('common_books_top_number', models.PositiveSmallIntegerField(verbose_name='количество популярных книг главной страницы')),
                ('num_reviews_per_page', models.PositiveIntegerField(verbose_name='количество отзывов на странице')),
                ('num_books_per_page', models.PositiveIntegerField(verbose_name='количество книг на странице')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
